vich_uploader:
    db_driver: orm
    metadata:
        type: attributes

    mappings:
        carrousel_images:
            uri_prefix: /images/carrousel
            upload_destination: '%kernel.project_dir%/public/images/carrousel'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
